# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'IOS-RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  	pod 'Alamofire'
 	  pod 'AlamofireObjectMapper'
 	  pod 'RxSwift'
 	  pod 'RxCocoa'
  	pod 'ObjectMapper'
		pod 'Kingfisher'


  # Pods for IOS-RxSwift

  target 'IOS-RxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS-RxSwiftUITests' do
    # Pods for testing
  end

end
